[build]
  command = "npm run build" # Команда, которая собирает ваш проект
  publish = "public" # Директория, из которой будет размещен статический контент (замените на свой путь)

[dev]
  framework = "express" # Укажите фреймворк Express.js
